version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: /home/jan/Coding/private/Docker/complex/nginx
    ports:
      - '3050:80'
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: /home/jan/Coding/private/Docker/complex/server
    volumes:
      - /home/node/app/node_modules
      - /home/jan/Coding/private/Docker/complex/server:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - /home/jan/Coding/private/Docker/complex/client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: /home/jan/Coding/private/Docker/complex/worker
    volumes:
      - /home/node/app/node_modules
      - /home/jan/Coding/private/Docker/complex/worker:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
