name: Test and Deploy

on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t jannnesss/complex-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true jannnesss/complex-test npm test

      - name: Build Docker image
        if: ${{ success() }}
        run: |
          docker build -t jannnesss/multi-client ./client
          docker build -t jannnesss/multi-nginx ./nginx
          docker build -t jannnesss/multi-server ./server
          docker build -t jannnesss/multi-worker ./worker
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push jannnesss:multi-client
          docker push jannnesss:multi-nginx
          docker push jannnesss:multi-server
          docker push jannnesss:multi-worker
      - name: Deploy test
        run: zip -r deploy.zip . -x '*.git*'